# Generated by Django 5.0.4 on 2024-06-04 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_timer', models.DurationField(verbose_name='Таймер ОС')),
                ('antivirus_timer', models.DurationField(verbose_name='Таймер Антивируса')),
                ('office_timer', models.DurationField(verbose_name='Таймер Офиса')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeEquipment',
            fields=[
                ('id_device', models.AutoField(primary_key=True, serialize=False, verbose_name='ID устройства')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(max_length=50, verbose_name='Категория')),
                ('status', models.CharField(max_length=50, verbose_name='Статус оборудования')),
                ('department', models.CharField(max_length=50, verbose_name='Отдел')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.DeleteModel(
            name='Computer',
        ),
    ]
