# Generated by Django 5.0.4 on 2024-06-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0007_alter_officeequipment_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officeequipment',
            name='department',
        ),
    ]
