# Generated by Django 5.0.4 on 2024-06-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0009_alter_officeequipment_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensetimer',
            options={'verbose_name': 'Срок', 'verbose_name_plural': 'Сроки'},
        ),
        migrations.AlterModelOptions(
            name='officeequipment',
            options={'verbose_name': 'Оборудование', 'verbose_name_plural': 'Оборудование'},
        ),
    ]
