# Generated by Django 5.0.4 on 2024-06-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0010_alter_licensetimer_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicenseTimer',
        ),
        migrations.DeleteModel(
            name='OfficeEquipment',
        ),
    ]
