# Generated by Django 5.0.4 on 2024-06-17 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('equipment_manager', '0011_delete_licensetimer_delete_officeequipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_timer', models.DateTimeField(verbose_name='Таймер ОС')),
                ('antivirus_timer', models.DateTimeField(verbose_name='Таймер Антивируса')),
                ('office_timer', models.DateTimeField(verbose_name='Таймер Офиса')),
            ],
            options={
                'verbose_name': 'Срок',
                'verbose_name_plural': 'Сроки',
            },
        ),
        migrations.CreateModel(
            name='OfficeEquipment',
            fields=[
                ('id_device', models.AutoField(primary_key=True, serialize=False, verbose_name='ID устройства')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('Компьютеры', 'Компьютеры'), ('Телефоны', 'Телефоны'), ('Принтер', 'Принтер'), ('Сканер', 'Сканер'), ('Копировальные аппараты', 'Копировальные аппараты'), ('Факсимильные аппараты', 'Факсимильные аппараты'), ('Многофункциональные устройства (МФУ)', 'Многофункциональные устройства (МФУ)'), ('Серверы', 'Серверы'), ('Плоттеры', 'Плоттеры'), ('Шредеры', 'Шредеры'), ('Калькуляторы', 'Калькуляторы'), ('Ноутбуки', 'Ноутбуки'), ('Мониторы', 'Мониторы'), ('Клавиатуры', 'Клавиатуры'), ('Мыши', 'Мыши'), ('Сетевое оборудование (роутеры, свитчи, хабы)', 'Сетевое оборудование (роутеры, свитчи, хабы)'), ('Источники бесперебойного питания (ИБП)', 'Источники бесперебойного питания (ИБП)'), ('Кабели и разъемы', 'Кабели и разъемы'), ('Картриджи и тонеры', 'Картриджи и тонеры'), ('Бумага и другие расходные материалы', 'Бумага и другие расходные материалы')], max_length=70, verbose_name='Категория')),
                ('status', models.CharField(choices=[('В работе', 'В работе'), ('В ремонте', 'В ремонте'), ('В запасе', 'В запасе'), ('Списана', 'Списана'), ('Неизвестно', 'Неизвестно'), ('В утилизации', 'В утилизации')], max_length=50, verbose_name='Статус оборудования')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group', to_field='name', verbose_name='Отдел')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
            },
        ),
    ]
