# Generated by Django 5.0.4 on 2024-06-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_manager', '0012_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensetimer',
            options={'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лицензии'},
        ),
    ]
