# Generated by Django 5.0.4 on 2024-05-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='status_storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_request', models.BigIntegerField()),
                ('id_employee', models.BigIntegerField()),
                ('request_from_date', models.DateField()),
                ('name_of_problem', models.CharField(max_length=80)),
                ('description_of_problem', models.CharField(max_length=256)),
                ('date_of_finish', models.DateField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_support.status_storage')),
            ],
        ),
    ]
