# Generated by Django 5.0.4 on 2024-05-17 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_emp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_request', models.BigIntegerField()),
                ('request_from_date', models.DateField()),
                ('name_of_problem', models.CharField(max_length=80)),
                ('description_of_problem', models.CharField(max_length=256)),
                ('status', models.CharField(blank=True, choices=[('Критично', 'Критично'), ('Не критично', 'Не критично')], max_length=50)),
                ('date_of_finish', models.DateField(blank=True, null=True)),
                ('nemployee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tech_support.employee')),
            ],
        ),
    ]
