# Generated by Django 5.0.4 on 2024-06-01 09:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0002_problems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='id',
        ),
        migrations.AlterField(
            model_name='problems',
            name='id_request',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
