# Generated by Django 5.0.4 on 2024-06-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0003_remove_problems_id_alter_problems_id_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='id_request',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
