# Generated by Django 5.0.4 on 2024-06-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0008_alter_problems_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='nemployee',
        ),
    ]
