# Generated by Django 5.0.4 on 2024-06-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0009_remove_problems_nemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='status',
            field=models.CharField(blank=True, choices=[('Открыта', 'Открыта'), ('В работе', 'В работе'), ('Выполнена', 'Выполнена'), ('Отклонена', 'Отклонена'), ('Ожидает', 'Ожидает'), ('На доработку', 'На доработку')], default='Открыта', max_length=50),
        ),
    ]
