# Generated by Django 5.0.4 on 2024-06-13 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0010_alter_problems_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='date_of_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='description_of_problem',
            field=models.CharField(max_length=256, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='id_request',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='name_of_problem',
            field=models.CharField(max_length=80, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='request_from_date',
            field=models.DateField(verbose_name='Дата обращения'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='status',
            field=models.CharField(blank=True, choices=[('Открыта', 'Открыта'), ('В работе', 'В работе'), ('Выполнена', 'Выполнена'), ('Отклонена', 'Отклонена'), ('Ожидает', 'Ожидает'), ('На доработку', 'На доработку')], default='Открыта', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
