# Generated by Django 5.0.4 on 2024-06-13 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0011_alter_problems_date_of_finish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='problems',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techsupport.status', verbose_name='Статус'),
        ),
    ]
