# Generated by Django 5.0.4 on 2024-06-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0012_status_alter_problems_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='status',
            field=models.CharField(blank=True, choices=[('Открыта', 'Открыта'), ('В работе', 'В работе'), ('Выполнена', 'Выполнена'), ('Отклонена', 'Отклонена'), ('Ожидает', 'Ожидает'), ('На доработку', 'На доработку')], default='Открыта', max_length=50, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
