# Generated by Django 5.0.4 on 2024-06-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0015_alter_problem_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
