# Generated by Django 5.0.4 on 2024-06-17 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('techsupport', '0016_delete_problem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id_request', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('request_from_date', models.DateField(verbose_name='Дата обращения')),
                ('name_of_problem', models.CharField(max_length=80, verbose_name='Наименование')),
                ('description_of_problem', models.CharField(max_length=256, verbose_name='Описание')),
                ('status', models.CharField(blank=True, choices=[('Открыта', 'Открыта'), ('В работе', 'В работе'), ('Выполнена', 'Выполнена'), ('Отклонена', 'Отклонена'), ('Ожидает', 'Ожидает'), ('На доработку', 'На доработку')], default='Открыта', max_length=50, verbose_name='Статус')),
                ('date_of_finish', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
