# Generated by Django 5.0.4 on 2024-06-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techsupport', '0019_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
